name: Build and Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - run: make
    - id: sha
      run:  echo "sha=$(git describe --always --tags --dirty)" >> $GITHUB_OUTPUT
    outputs:
      sha: ${{ steps.sha.outputs.sha }}

  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v1
      with:
        go-version: '1.21'
    - run: make generate-all
    - run: git diff --exit-code

  push:
    name: docker build and push images
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64, linux/arm, linux/amd64
          push: ${{github.ref_name == 'main'}}
          tags: |-
            ghcr.io/leonnicolas/gooki:latest
            ghcr.io/leonnicolas/gooki:${{ needs.build.outputs.sha }}
